export const View = {
  CHANGE_ACTIVE_TAB_ID: "VIEW_CHANGE_ACTIVE_TAB_ID",
}

export const Recipes = {
  FETCH_RECIPES_LIST: "RECIPES_FETCH_RECIPES_LIST",
  SELECT_RECIPE_ID: "RECIPES_SELECT_RECIPE_ID",
  GET_INGREDIENTS: "RECIPES_GET_INGREDIENTS",
}