export const View = {
  CHANGE_ACTIVE_TAB_ID: "VIEW_CHANGE_ACTIVE_TAB_ID",
}

export const Recipes = {
  FETCH_RECIPES_LIST: "RECIPES_FETCH_RECIPES_LIST",
  FETCH_RECIPES_LIST_SUCCESS: "RECIPES_FETCH_RECIPES_LIST_SUCCESS",
  FETCH_RECIPES_LIST_ERROR: "RECIPES_FETCH_RECIPES_LIST_ERROR",
  SELECT_RECIPE_ID: "RECIPES_SELECT_RECIPE_ID",
  GET_INGREDIENTS: "RECIPES_GET_INGREDIENTS",
  GET_INGREDIENTS_SUCCESS: "RECIPES_GET_INGREDIENTS_SUCCESS",
  GET_INGREDIENTS_ERROR: "RECIPES_GET_INGREDIENTS_ERROR",
  SUBMIT_UPDATE: "RECIPES_SUBMIT_UPDATE",
  SUBMIT_UPDATE_SUCCESS: "RECIPES_SUBMIT_UPDATE_SUCCESS",
  SUBMIT_UPDATE_ERROR: "RECIPES_SUBMIT_UPDATE_ERROR",
}